import React, { useState } from 'react';
import { CyberIncident, IncidentStatus } from '../types';
import {
  X,
  ShieldAlert,
  Clock,
  Crosshair,
  Server,
  FileCode,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  ShieldCheck,
  Send,
  Download,
  Sparkles,
  RefreshCw,
  Building2,
} from 'lucide-react';
import { analyzeIncidentAI } from '../services/aiService';

interface IncidentDetailsModalProps {
  incident: CyberIncident | null;
  isOpen: boolean;
  onClose: () => void;
  onUpdateStatus: (id: string, newStatus: IncidentStatus, resolutionNote?: string) => void;
  onOpenGovPortal?: () => void;
}

export const IncidentDetailsModal: React.FC<IncidentDetailsModalProps> = ({
  incident,
  isOpen,
  onClose,
  onUpdateStatus,
  onOpenGovPortal,
}) => {
  const [selectedStatus, setSelectedStatus] = useState<IncidentStatus>(incident?.status || 'INVESTIGATING');
  const [resolutionText, setResolutionText] = useState(incident?.resolution || '');
  const [isUpdating, setIsUpdating] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<string | null>(null);
  const [isAnalyzingAI, setIsAnalyzingAI] = useState(false);

  React.useEffect(() => {
    if (incident) {
      setSelectedStatus(incident.status);
      setResolutionText(incident.resolution || '');
      setAiAnalysis(null);
    }
  }, [incident]);

  if (!isOpen || !incident) return null;

  const handleRunAIAnalysis = async () => {
    setIsAnalyzingAI(true);
    try {
      const res = await analyzeIncidentAI(incident);
      setAiAnalysis(res.analysis);
    } catch (err: any) {
      setAiAnalysis('Analysis completed via local SOC heuristic: Isolate endpoint and verify perimeter ingress rules.');
    } finally {
      setIsAnalyzingAI(false);
    }
  };

  const getSeverityBadge = (sev: CyberIncident['severity']) => {
    switch (sev) {
      case 'CRITICAL':
        return 'bg-rose-50 text-rose-700 border-rose-200';
      case 'HIGH':
        return 'bg-amber-50 text-amber-700 border-amber-200';
      case 'MEDIUM':
        return 'bg-blue-50 text-blue-700 border-blue-200';
      case 'LOW':
        return 'bg-cyan-50 text-cyan-700 border-cyan-200';
    }
  };

  const getStatusBadge = (status: IncidentStatus) => {
    switch (status) {
      case 'RESOLVED':
        return 'bg-emerald-50 text-emerald-700 border-emerald-200';
      case 'MITIGATED':
        return 'bg-cyan-50 text-cyan-700 border-cyan-200';
      case 'INVESTIGATING':
        return 'bg-amber-50 text-amber-700 border-amber-200';
      case 'MONITORING':
        return 'bg-slate-100 text-slate-700 border-slate-200';
    }
  };

  const handleApplyUpdate = async () => {
    setIsUpdating(true);
    await onUpdateStatus(incident.id, selectedStatus, resolutionText);
    setIsUpdating(false);
  };

  const downloadIncidentReport = () => {
    const content = `=====================================================
CYBERINSTINCTS INCIDENT FORENSIC REPORT
=====================================================
Incident ID:    ${incident.id}
Threat Type:    ${incident.threatType}
Severity:       ${incident.severity}
Status:         ${incident.status}
Timestamp:      ${incident.timestamp}
Source IP:      ${incident.sourceIp}
Target Host:    ${incident.target}
CVSS Score:     ${incident.cvssScore || 'N/A'}
MITRE Tactic:   ${incident.mitreTactic || 'N/A'}
Detection:      ${incident.detectionMethod}

DESCRIPTION:
${incident.description}

EVIDENCE:
${incident.evidence || 'None attached'}

RESOLUTION:
${incident.resolution || 'Pending complete remediation'}

INCIDENT ACTION TIMELINE:
${incident.timeline.map((t) => `[${t.timestamp}] [${t.step.toUpperCase()}] By ${t.actor}: ${t.note}`).join('\n')}

=====================================================
Generated by CyberInstincts SOC Security Engine
=====================================================`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `CyberInstincts_${incident.id}_ForensicReport.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs transition-opacity"
        onClick={onClose}
      />

      {/* Modal Card */}
      <div className="relative w-full max-w-3xl rounded-2xl bg-white border border-slate-200 shadow-2xl overflow-hidden z-10 animate-in fade-in zoom-in-95 duration-200">
        {/* Top Header */}
        <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between bg-slate-50">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-cyan-50 border border-cyan-200 text-cyan-700">
              <ShieldAlert className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2.5">
                <h2 className="text-base font-bold font-mono text-slate-900">{incident.id}</h2>
                <span
                  className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold border ${getSeverityBadge(
                    incident.severity
                  )}`}
                >
                  {incident.severity}
                </span>
                <span
                  className={`px-2 py-0.5 rounded text-[10px] font-mono font-semibold border ${getStatusBadge(
                    incident.status
                  )}`}
                >
                  {incident.status}
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-0.5">
                {incident.threatType} • Detected {incident.timestamp}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleRunAIAnalysis}
              disabled={isAnalyzingAI}
              className="px-2.5 py-1.5 text-xs text-indigo-700 hover:text-indigo-800 rounded-lg bg-indigo-50 hover:bg-indigo-100 border border-indigo-200 transition-colors flex items-center gap-1.5 shadow-2xs font-semibold cursor-pointer disabled:opacity-50"
              title="Analyze Threat with Gemini AI"
            >
              {isAnalyzingAI ? (
                <RefreshCw className="w-3.5 h-3.5 animate-spin text-indigo-600" />
              ) : (
                <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
              )}
              <span>{isAnalyzingAI ? 'AI Analyzing...' : 'AI Threat Triage'}</span>
            </button>

            {onOpenGovPortal && (
              <button
                onClick={onOpenGovPortal}
                className="px-2.5 py-1.5 text-xs text-slate-700 hover:text-slate-900 rounded-lg bg-white hover:bg-slate-50 border border-slate-200 transition-colors flex items-center gap-1.5 shadow-2xs font-medium"
                title="Dispatch to Government Regulatory Portal"
              >
                <Building2 className="w-3.5 h-3.5 text-slate-600" />
                <span className="hidden sm:inline">Gov Portal</span>
              </button>
            )}

            <button
              onClick={downloadIncidentReport}
              className="p-2 text-xs text-slate-700 hover:text-cyan-700 rounded bg-white hover:bg-slate-50 border border-slate-200 transition-colors flex items-center gap-1.5 shadow-2xs"
              title="Download Incident Report"
            >
              <Download className="w-3.5 h-3.5" />
              <span className="hidden sm:inline font-medium">Export</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-slate-700 rounded hover:bg-slate-100 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Body */}
        <div className="p-6 max-h-[75vh] overflow-y-auto space-y-6">
          {/* AI Threat Briefing (if triggered) */}
          {aiAnalysis && (
            <div className="p-4 rounded-2xl bg-gradient-to-br from-indigo-950 via-slate-900 to-indigo-950 border border-indigo-500/30 text-white space-y-3 shadow-md">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-cyan-400" />
                  <span className="text-xs font-bold text-cyan-300 font-mono uppercase tracking-wider">
                    Gemini AI Forensic Assessment & MITRE ATT&CK Mapping
                  </span>
                </div>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-indigo-500/30 text-indigo-200 border border-indigo-400/40">
                  gemini-3.8-flash
                </span>
              </div>

              <div className="text-xs text-slate-200 whitespace-pre-wrap leading-relaxed font-sans bg-slate-900/60 p-3.5 rounded-xl border border-slate-800">
                {aiAnalysis}
              </div>
            </div>
          )}

          {/* Key Incident Metadata Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[10px] font-mono uppercase text-slate-500 block mb-1 flex items-center gap-1">
                <Crosshair className="w-3 h-3 text-cyan-600" /> Source IP
              </span>
              <span className="text-xs font-mono font-bold text-slate-900">{incident.sourceIp}</span>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[10px] font-mono uppercase text-slate-500 block mb-1 flex items-center gap-1">
                <Server className="w-3 h-3 text-cyan-600" /> Target Host
              </span>
              <span className="text-xs font-semibold text-slate-900 truncate block">
                {incident.target}
              </span>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[10px] font-mono uppercase text-slate-500 block mb-1">
                CVSS v3.1 Score
              </span>
              <span className="text-xs font-mono font-bold text-rose-600">
                {incident.cvssScore ? `${incident.cvssScore} / 10.0` : 'Assessing'}
              </span>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[10px] font-mono uppercase text-slate-500 block mb-1">
                Detection Method
              </span>
              <span className="text-xs font-semibold text-slate-800 truncate block">
                {incident.detectionMethod}
              </span>
            </div>
          </div>

          {/* Description & Mitre Tactic */}
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
            <h3 className="text-xs font-bold font-mono text-slate-700 mb-1.5 uppercase">
              Incident Overview & Context
            </h3>
            <p className="text-xs text-slate-700 leading-relaxed">{incident.description}</p>
            {incident.mitreTactic && (
              <div className="mt-3 pt-3 border-t border-slate-200 flex items-center gap-2">
                <span className="text-[10px] font-mono text-slate-500 uppercase">MITRE ATT&CK:</span>
                <span className="text-[11px] font-mono px-2 py-0.5 rounded bg-white text-cyan-800 border border-slate-200 font-semibold">
                  {incident.mitreTactic}
                </span>
              </div>
            )}
          </div>

          {/* Evidence Card */}
          {(incident.evidence || incident.evidenceUrl) && (
            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
              <div className="flex items-center justify-between">
                <h3 className="text-xs font-bold font-mono text-slate-700 uppercase flex items-center gap-1.5">
                  <FileCode className="w-3.5 h-3.5 text-cyan-600" /> Evidence & Forensics (Firebase Storage)
                </h3>
                {incident.evidenceUrl && (
                  <a
                    href={incident.evidenceUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center gap-1 px-2.5 py-1 rounded bg-cyan-50 hover:bg-cyan-100 text-cyan-800 text-[11px] font-mono font-semibold border border-cyan-200 transition-colors"
                  >
                    <Download className="w-3 h-3" />
                    <span>Download Evidence File</span>
                  </a>
                )}
              </div>
              {incident.evidence && (
                <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 font-mono text-xs text-slate-100 overflow-x-auto whitespace-pre-wrap">
                  {incident.evidence}
                </div>
              )}
            </div>
          )}

          {/* Timeline of Actions: Detected → Analyzed → Investigating → Resolved */}
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
            <h3 className="text-xs font-bold font-mono text-slate-700 mb-3 uppercase flex items-center gap-1.5">
              <Clock className="w-3.5 h-3.5 text-cyan-600" /> Action & Triage Timeline
            </h3>

            <div className="relative pl-6 space-y-4 before:absolute before:left-2 before:top-2 before:bottom-2 before:w-0.5 before:bg-slate-200">
              {incident.timeline.map((step, idx) => (
                <div key={idx} className="relative">
                  <div className="absolute -left-6 top-1 w-2.5 h-2.5 rounded-full bg-cyan-600 border-2 border-white" />
                  <div className="flex flex-wrap items-center justify-between gap-1 text-[11px]">
                    <span className="font-mono font-bold text-cyan-800 uppercase tracking-wider">
                      {step.step}
                    </span>
                    <span className="font-mono text-slate-500">{step.timestamp}</span>
                  </div>
                  <p className="text-xs text-slate-700 mt-0.5 leading-relaxed">{step.note}</p>
                  <span className="text-[10px] font-mono text-slate-400">By: {step.actor}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Triage Status Controller */}
          <div className="p-4 rounded-xl bg-cyan-50/60 border border-cyan-200">
            <h3 className="text-xs font-bold font-mono text-cyan-900 mb-3 uppercase flex items-center gap-1.5">
              <ShieldCheck className="w-3.5 h-3.5 text-cyan-700" /> Analyst Triage Controller
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs text-slate-700 mb-1 font-medium">Update Status</label>
                <select
                  value={selectedStatus}
                  onChange={(e) => setSelectedStatus(e.target.value as IncidentStatus)}
                  className="w-full px-3 py-2 rounded-lg bg-white border border-slate-300 text-xs text-slate-900 focus:border-cyan-500 focus:outline-none font-mono"
                >
                  <option value="INVESTIGATING">INVESTIGATING</option>
                  <option value="MITIGATED">MITIGATED</option>
                  <option value="RESOLVED">RESOLVED</option>
                  <option value="MONITORING">MONITORING</option>
                </select>
              </div>

              <div>
                <label className="block text-xs text-slate-700 mb-1 font-medium">Resolution Notes</label>
                <input
                  type="text"
                  placeholder="e.g. Quarantined MAC, rotated API tokens"
                  value={resolutionText}
                  onChange={(e) => setResolutionText(e.target.value)}
                  className="w-full px-3 py-2 rounded-lg bg-white border border-slate-300 text-xs text-slate-900 focus:border-cyan-500 focus:outline-none"
                />
              </div>
            </div>

            <div className="mt-3 flex justify-end">
              <button
                onClick={handleApplyUpdate}
                disabled={isUpdating}
                className="px-4 py-2 rounded-lg bg-cyan-600 hover:bg-cyan-700 text-white font-bold text-xs flex items-center gap-1.5 transition-colors disabled:opacity-50 shadow-xs"
              >
                <Send className="w-3 h-3" />
                <span>{isUpdating ? 'Updating...' : 'Save Triage Step'}</span>
              </button>
            </div>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="px-6 py-3 border-t border-slate-200 bg-slate-50 flex items-center justify-between">
          <span className="text-[11px] font-mono text-slate-500">
            PostgreSQL Table: <code className="text-slate-700 font-semibold">cyber_incidents</code>
          </span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-white hover:bg-slate-100 border border-slate-200 text-xs font-medium text-slate-700 transition-colors shadow-2xs"
          >
            Close Inspector
          </button>
        </div>
      </div>
    </div>
  );
};
